The Daniel Dilemma
tagmein/gbsp pull request #111
Opened 2024-02-10 07:21 UTC by Vikulakav

2024-02-11 21:06 UTC, NateFerrero commented on content/book41.md
> +##### How can a person apply the information in this book to live a better life?
```suggestion

##### How can a person apply the information in this book to live a better life?

```

2024-02-11 21:06 UTC, NateFerrero commented on content/book41.md
> +##### What is a reason that a person might want to read this book?
```suggestion

##### What is a reason that a person might want to read this book?

```

2024-02-11 21:07 UTC, NateFerrero commented on content/book41.md
> +##### Similar books to this book?
```suggestion

##### Similar books to this book?

```

2024-02-11 21:09 UTC, NateFerrero requested changes
Missing section

```
##### Tags that apply to this book
```

2024-02-12 00:34 UTC, Vikulakav commented
The book does not have tags, you can check it here despite having the title the points listed are not tags but similar books
![image](https://github.com/tagmein/gbsp/assets/90867480/f20943d2-4c08-493a-abda-e227917b7816)

2024-02-12 01:43 UTC, closed without merging